CREATE TABLE Professor (
	PSSN CHAR(10),
	Name VARCHAR(50),
	Age INTEGER,
	Gender VARCHAR(50),
	Rank INTEGER,
	Speciality VARCHAR(50),
	PRIMARY KEY(PSSN)
);
	
CREATE TABLE Dapartment(
	dno INTEGER,
	dname VARCHAR(50),
	Office VARCHAR(50),
	PRIMARY KEY(dno)
	);
	
CREATE TABLE Project(
	PID INTEGER,
	Sponsor CHAR(10),
	START_DATE DATE,
	END_DATE DATE,
	Budget DECIMAL,
	PRIMARY KEY(PID)
	);
	

CREATE TABLE Student(
	SSSN CHAR(10),
	Name VARCHAR(50),
	Age INTEGER,
	Gender VARCHAR(10),
	Degree_Prog VARCHAR(50),
	Major INTEGER,
	PRIMARY KEY(SSSN),
	FOREIGN KEY (Major) REFERENCES Dapartment(dno) 
	ON DELETE RESTRICT
	ON UPDATE CASCADE
	);


	
CREATE TABLE runs(
	dno INTEGER,
	PSSN CHAR(10),
	PRIMARY KEY(dno,PSSN),
	FOREIGN KEY (dno) REFERENCES Dapartment(dno) ON DELETE RESTRICT ON UPDATE CASCADE,
	FOREIGN KEY (PSSN) REFERENCES Professor(PSSN) ON DELETE RESTRICT ON UPDATE CASCADE
	);
	
CREATE TABLE work_department(
	dno INTEGER,
	PSSN CHAR(10)PRIMARY KEY ,
	FOREIGN KEY (dno) REFERENCES Dapartment(dno) ON DELETE RESTRICT ON UPDATE CASCADE,
	FOREIGN KEY (PSSN) REFERENCES Professor(PSSN)  ON DELETE RESTRICT ON UPDATE CASCADE
	);
	
	
CREATE TABLE Manage_Proj(
	PID INTEGER PRIMARY KEY,
	PSSN CHAR(10),
	FOREIGN KEY (PID) REFERENCES Project(PID)ON DELETE CASCADE,
	FOREIGN KEY (PSSN) REFERENCES Professor(PSSN)
	);
	
CREATE TABLE work_Proj(
	PID INTEGER,
	PSSN CHAR(10),
	PRIMARY KEY(PID,PSSN),
	FOREIGN KEY (PID) REFERENCES Project(PID) ON DELETE CASCADE,
	FOREIGN KEY (PSSN) REFERENCES Professor(PSSN) ON DELETE RESTRICT
	);	
			
	